version: '3.9'

services:
  web:
    build: .
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./static:/app/static  # Монтируем локальную папку static внутрь контейнера

  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-d", "1"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./templates/css:/usr/share/nginx/html/css
      - ./templates/js:/usr/share/nginx/html/js
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: